# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b06597f7476c15361a17ac1d94ef711f7d85e220ef2dddb92041bbc9a0433996b0dabda1935a15e528574798ab011c92f208fc19094355c3333dbc6a6c058c09

test:
  secret_key_base: ca70934479721d08eee499a5bc8e4e3dcbf87727f4a366da4293cafc26f804637a06e22678ad593be1f43b545f31637aebd467e73d5b497dad9068e1bdce6648

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
